name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    environment: production 

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar sesión en el registro de Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y etiquetar la imagen Docker
        run: |
          docker build -t isax0102/graphql-nest:latest .
          docker push isax0102/graphql-nest:latest
      - name: Instalar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - name: Instalar Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Desplegar Secretos y ConfigMaps
        run: |
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/configmap.yaml
          
      # - name: Desplegar PostgreSQL
      #   run: |
      #     kubectl apply -f k8s/postgres-deployment.yaml
      #     kubectl delete pod postgres-fbb5df87c-lrhj7
      #     kubectl rollout status deployment/postgres --timeout=120s
      # - name: Verificar estado de PostgreSQL
      #   if: failure()
      #   run: |
      #     echo "Inspeccionando el estado del pod..."
      #     kubectl get pods -l app=postgres
      #     echo "Detalles del pod:"
      #     kubectl describe pod -l app=postgres
      #     echo "Logs del contenedor:"
      #     kubectl logs -l app=postgres
          
      # - name: Desplegar RabbitMQ
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm upgrade --install my-rabbitmq bitnami/rabbitmq \
      #       --set auth.username=isax01 \
      #       --set auth.password=isax
      #     kubectl rollout status statefulset/my-rabbitmq
      - name: Desplegar Aplicación Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl rollout status deployment/graphql-nest --timeout=120s
      - name: Verificar estado de Backend
        if: failure()
        run: |
          echo "Inspeccionando el estado del pod..."
          kubectl get pods -l app=graphql-nest
          POD_NAME=$(kubectl get pods -l app=graphql-nest -o=jsonpath='{.items[0].metadata.name}')
          echo "Detalles del pod:"
          kubectl describe pod $POD_NAME
          echo "Logs del contenedor:"
          kubectl logs $POD_NAME

